#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AppEvent {
    MicToggled,
    ResetRequested,
    WindowLargerRequested,
    WindowSmallerRequested,
    WindowResizeRequested { width: i32, height: i32 },
    WindowMoveToNextScreenRequested,
    FixtureInjectRequested(u8),
    LogMessage(String),
    LiveText(String),
    CommitRequested,
    RecordingStartRejected,
    SettingsToggled,
    SilenceAutoStopSecondsChanged(u64),
    VadSilenceDurationMsChanged(u32),
    VisibilityToggled,
    ShowRequested,
    HideRequested,
    CopyRequested,
    QuitRequested,
    RuntimeError(String),
    ErrorCleared,
}
